from app.models.usuario import Usuario  # noqa: F401
from app.models.curso import Curso  # noqa: F401
from app.models.estudante import Estudante  # noqa: F401
from app.models.professor import Professor  # noqa: F401
from app.models.disciplina import Disciplina  # noqa: F401
from app.models.turma import Turma  # noqa: F401
from app.models.matricula import Matricula  # noqa: F401
from app.models.nota import Nota  # noqa: F401
from app.models.frequencia import Frequencia  # noqa: F401